version: "3.8"

services:
  browser-app:
    build:
      context: ./node
      target: browser-app
    ports:
      - "80:80"
    depends_on:
      - python-app

  python-app:
    build:
      context: ./python
      target: python-app
    ports:
      - "8081:8081"

  java-app:
    build:
      context: ./java
      target: java-app
    ports:
      - "8082:8080"
    depends_on:
      - oracle-db

  oracle-db:
      image: container-registry.oracle.com/database/express:latest
      environment:
        - ORACLE_PWD=TaxService123
      ports:
        - "1521:1521"
      volumes:
        - oracle-data:/opt/oracle/oradata
      healthcheck:
        test: ["CMD-SHELL", "echo 'select 1 from dual;' | sqlplus -s SYSTEM/TaxService123@localhost:1521/xe"]
        interval: 30s
        timeout: 10s
        retries: 10

volumes:
  oracle-data:

networks:
  default:
    name: tax-agent-network
