version: "3.8"

services:
  server:
    build:
      context: ./node
      target: server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  browser-app:
    build:
      context: ./node
      target: browser-app
    ports:
      - "80:80"
    depends_on:
      - server

  python-app:
    build:
      context: ./python
      target: python-app
    ports:
      - "8081:8081"

  java-app:
    build:
      context: ./java
      target: java-app

  oracle-db:
      image: container-registry.oracle.com/database/express:latest
      environment:
        - ORACLE_SID=TaxService
        - ORACLE_PDB=ORCLPDB1
        - ORACLE_PWD=TaxService123
      ports:
        - "1521:1521"
      volumes:
        - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:

networks:
  default:
    name: tax-agent-network
