version: "3.8"

services:
  server:
    build:
      context: ./node
      target: server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  browser-app:
    build:
      context: ./node
      target: browser-app
    ports:
      - "80:80"
    depends_on:
      - server

  python-app:
    build:
      context: ./python
      target: python-app
    ports:
      - "8081:8081"

networks:
  default:
    name: tax-agent-network
