version: "3.8"

services:
  server:
    build:
      context: .
      target: server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

networks:
  default:
    name: tax-agent-network
