version: "3.8"

services:
  server:
    build:
      context: .
      target: server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  browser-app:
    build:
      context: .
      target: browser-app
    ports:
      - "80:80"
    depends_on:
      - server

networks:
  default:
    name: tax-agent-network
